spring:
  datasource:
    url: jdbc:h2:mem:interstellar_gateway
    driverClassName: org.h2.Driver
    username: interstellar
    password: '*^|1BRSEW8@N>a'
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
